"""Run production Backup/BackupManager/SyncSnapshot with real Gson and transactional DAO doubles.
No device/network/user database is touched. Requires JDK 21 and a Gson jar in ~/.gradle,
or --gson-jar. --source-root supports old-source negative controls.
"""
from pathlib import Path
from tempfile import TemporaryDirectory
import argparse, subprocess
ROOT=Path(__file__).resolve().parents[2]
STUBS={
'android/util/Log.java':'package android.util;public class Log{public static int e(String a,String b,Throwable c){return 0;}public static int w(String a,String b,Throwable c){return 0;}}',
'androidx/annotation/NonNull.java':'package androidx.annotation;public @interface NonNull{}',
'android/content/SharedPreferences.java':'''package android.content;import java.util.*;public class SharedPreferences {
 public final Map<String,Object> data=new HashMap<>();public int failCommits;
 public Map<String,?> getAll(){return new HashMap<>(data);}public Editor edit(){return new Editor();}
 public class Editor {Map<String,Object> changes=new HashMap<>();boolean clear;
 public Editor clear(){clear=true;return this;}public Editor putString(String k,String v){changes.put(k,v);return this;}public Editor putBoolean(String k,boolean v){changes.put(k,v);return this;}public Editor putFloat(String k,float v){changes.put(k,v);return this;}public Editor putLong(String k,long v){changes.put(k,v);return this;}public Editor putInt(String k,int v){changes.put(k,v);return this;}public Editor putStringSet(String k,Set<String> v){changes.put(k,new HashSet<>(v));return this;}
 public boolean commit(){if(clear)data.clear();data.putAll(changes);if(failCommits>0){failCommits--;return false;}return true;}
 }}''',
'com/github/catvod/utils/Prefers.java':'''package com.github.catvod.utils;public class Prefers {static final android.content.SharedPreferences prefs=new android.content.SharedPreferences();public static android.content.SharedPreferences getPrefers(){return prefs;}public static void put(String k,Object v){prefs.data.put(k,v);}}''',
'com/fongmi/android/tv/App.java':'package com.fongmi.android.tv;public class App{static final com.google.gson.Gson gson=new com.google.gson.Gson();public static com.google.gson.Gson gson(){return gson;}public static void post(Runnable r){r.run();}}',
'com/fongmi/android/tv/utils/Task.java':'package com.fongmi.android.tv.utils;public class Task{public static void executeSerial(Runnable r){r.run();}}',
'com/fongmi/android/tv/impl/Callback.java':'package com.fongmi.android.tv.impl;public class Callback{public void success(){}public void error(){}}',
'com/fongmi/android/tv/utils/Formatters.java':'package com.fongmi.android.tv.utils;public class Formatters{public static java.time.format.DateTimeFormatter DATE=java.time.format.DateTimeFormatter.ISO_LOCAL_DATE;}',
'com/fongmi/android/tv/utils/FileUtil.java':'package com.fongmi.android.tv.utils;public class FileUtil{public static String incoming;public static String readGzip(java.io.File f){return incoming;}public static boolean gzipCompress(byte[] b,java.io.File f){return true;}}',
'com/github/catvod/utils/Path.java':'package com.github.catvod.utils;public class Path{public static java.io.File backup(){return new java.io.File(".");}public static java.io.File tv(){return backup();}public static java.util.List<java.io.File> list(java.io.File f){return java.util.List.of();}public static void clear(java.io.File f){}public static void move(java.io.File a,java.io.File b)throws java.io.IOException{}}',
'com/fongmi/android/tv/bean/Config.java':'''package com.fongmi.android.tv.bean;import com.fongmi.android.tv.db.*;import com.fongmi.android.tv.App;import java.util.*;public class Config{public int id,type;public String url,name;public int getId(){return id;}public int getType(){return type;}public String getUrl(){return url==null?"":url;}public static Config objectFrom(String s){return App.gson().fromJson(s,Config.class);}public static List<Config> findUrls(){return AppDatabase.get().getConfigDao().findAll().stream().filter(c->c.type==0).toList();}public static Config find(Config target){var existing=AppDatabase.get().getConfigDao().find(target.getUrl(),target.type);if(existing!=null)return existing;var copy=App.gson().fromJson(App.gson().toJson(target),Config.class);copy.id=100+AppDatabase.get().getConfigDao().items.size();AppDatabase.get().getConfigDao().insertOrUpdate(List.of(copy));return copy;}}''',
'com/fongmi/android/tv/bean/History.java':'''package com.fongmi.android.tv.bean;import com.fongmi.android.tv.db.*;import java.util.*;public class History{public String key,vodName;public int cid;public String getKey(){return key;}public int getCid(){return cid;}public String getVodName(){return vodName;}public static List<History> get(int cid){return AppDatabase.get().getHistoryDao().items.stream().filter(h->h.cid==cid).toList();}public static void delete(int cid){AppDatabase.get().getHistoryDao().delete(cid);}public History cid(int value){cid=value;key=key.substring(0,key.lastIndexOf(AppDatabase.SYMBOL)+AppDatabase.SYMBOL.length())+value;return this;}public void save(){AppDatabase.get().getHistoryDao().insertOrUpdate(List.of(this));}}''',
'com/fongmi/android/tv/bean/Keep.java':'''package com.fongmi.android.tv.bean;import com.fongmi.android.tv.db.*;import java.util.*;public class Keep{public String key;public int cid,type;public String getKey(){return key;}public int getCid(){return cid;}public int getType(){return type;}public static List<Keep> getVod(){return AppDatabase.get().getKeepDao().items.stream().filter(k->k.type==0).toList();}public static void deleteAll(){AppDatabase.get().getKeepDao().items.removeIf(k->k.type==0);}public static void sync(List<Config> configs,List<Keep> keep){for(var k:keep){var c=configs.stream().filter(i->i.id==k.cid).findFirst().orElseThrow();k.cid=Config.find(c).id;k.key=k.key.substring(0,k.key.lastIndexOf(AppDatabase.SYMBOL)+AppDatabase.SYMBOL.length())+k.cid;AppDatabase.get().getKeepDao().insertOrUpdate(List.of(k));}}}''',
'com/fongmi/android/tv/db/AppDatabase.java':'''package com.fongmi.android.tv.db;import com.fongmi.android.tv.bean.*;import java.util.*;public class AppDatabase{
 public static final String SYMBOL="@@@";static final AppDatabase DB=new AppDatabase();public static AppDatabase get(){return DB;}public String failTable;public int failAfter,writes;public boolean failCommit;
 public class Dao<T>{public List<T> items=new ArrayList<>();String name;Dao(String n){name=n;}public List<T> findAll(){return new ArrayList<>(items);}public void deleteAllForRestore(){items.clear();}public void delete(){items.clear();}public void delete(int cid){items.removeIf(i->i instanceof History h&&h.cid==cid);}public void insertOrUpdate(List<T> list){for(T value:list){if(name.equals(failTable)&&failAfter--==0){failTable=null;throw new IllegalStateException("injected "+name+" insert failure");}writes++;items.add(value);}}}
 public class ConfigDao extends Dao<Config>{ConfigDao(){super("Config");}public Config find(String url,int type){return items.stream().filter(c->c.type==type&&url.equals(c.getUrl())).findFirst().orElse(null);}public Config findById(int id){return items.stream().filter(c->c.id==id).findFirst().orElse(null);}}
 Dao<Site> site=new Dao<>("Site");Dao<Live> live=new Dao<>("Live");Dao<Keep> keep=new Dao<>("Keep");ConfigDao config=new ConfigDao();Dao<History> history=new Dao<>("History");Dao<Device> device=new Dao<>("Device");Dao<Track> track=new Dao<>("Track");
 public Dao<Site> getSiteDao(){return site;}public Dao<Live> getLiveDao(){return live;}public Dao<Keep> getKeepDao(){return keep;}public ConfigDao getConfigDao(){return config;}public Dao<History> getHistoryDao(){return history;}public Dao<Device> getDeviceDao(){return device;}public Dao<Track> getTrackDao(){return track;}
 public List<Dao<?>> all(){return List.of(site,live,keep,config,history,device,track);}public void clearAllTables(){all().forEach(d->d.items.clear());}
 @SuppressWarnings({"rawtypes","unchecked"})public void runInTransaction(Runnable r){var tables=all();var before=tables.stream().map(d->new ArrayList<>(d.items)).toList();try{r.run();if(failCommit){failCommit=false;throw new IllegalStateException("injected commit failure");}}catch(RuntimeException e){for(int i=0;i<tables.size();i++)((Dao)tables.get(i)).items=new ArrayList(before.get(i));throw e;}}
}''',
'okhttp3/Response.java':'''package okhttp3;public class Response implements AutoCloseable{int code;String json;public boolean closed;public Response(int code,String json){this.code=code;this.json=json;}public boolean isSuccessful(){return code>=200&&code<300;}public int code(){return code;}public Body body(){return json==null?null:new Body();}public void close(){closed=true;}public class Body{public java.io.InputStream byteStream(){return new java.io.ByteArrayInputStream(json.getBytes(java.nio.charset.StandardCharsets.UTF_8));}}}''',
'DataSafetyProbe.java':r'''import com.fongmi.android.tv.bean.*;import com.fongmi.android.tv.db.*;import com.fongmi.android.tv.App;import com.github.catvod.utils.Prefers;import com.fongmi.android.tv.utils.FileUtil;import java.util.*;
public class DataSafetyProbe{
 static final AppDatabase db=AppDatabase.get();static final android.content.SharedPreferences prefs=Prefers.getPrefers();
 static void check(boolean v,String m){if(!v)throw new AssertionError(m);}static String state(){return App.gson().toJson(db.all().stream().map(d->d.items).toList());}
 static void seed(){db.clearAllTables();db.failTable=null;db.failCommit=false;db.writes=0;prefs.failCommits=0;prefs.data.clear();prefs.data.put("theme","original");prefs.data.put("long",9L);prefs.data.put("float",1.25f);prefs.data.put("set",new HashSet<>(List.of("before")));db.getConfigDao().items.add(App.gson().fromJson("{id:10,type:0,url:'https://owned/source'}",Config.class));db.getHistoryDao().items.add(App.gson().fromJson("{key:'s@@@old@@@10',cid:10,vodName:'Old'}",History.class));db.getHistoryDao().items.add(App.gson().fromJson("{key:'s@@@other@@@11',cid:11,vodName:'Other'}",History.class));db.getKeepDao().items.add(App.gson().fromJson("{key:'s@@@old@@@10',cid:10,type:0}",Keep.class));db.getKeepDao().items.add(App.gson().fromJson("{key:'live',cid:0,type:1}",Keep.class));db.getSiteDao().items.add(new Site());db.getLiveDao().items.add(new Live());db.getDeviceDao().items.add(new Device());db.getTrackDao().items.add(new Track());}
 static boolean restore()throws Exception{var m=BackupManager.class.getDeclaredMethod("restore",java.io.File.class);m.setAccessible(true);return (boolean)m.invoke(null,new java.io.File("fixture.tv"));}
 static void backup()throws Exception{
  for(String table:List.of("Site","Live","Keep","Config","History")){
   seed();String before=state();Map<String,?> old=prefs.getAll();FileUtil.incoming="{site:[{}],live:[{}],keep:[{key:'x'}],config:[{id:30,url:'new'}],history:[{key:'new'}],prefers:{theme:'incoming'}}";db.failTable=table;db.failAfter=0;check(!restore(),"failed restore reported success");check(state().equals(before),table+" failed restore changed original tables (including Device/Track)");check(prefs.getAll().equals(old),"failed restore changed prefs");
  }
  seed();String before=state();Map<String,?> old=prefs.getAll();FileUtil.incoming="{config:[],prefers:{theme:{invalid:1}}}";check(!restore()&&state().equals(before)&&prefs.getAll().equals(old),"invalid prefs not rejected before mutation");
  for(boolean failDb:List.of(false,true)){seed();before=state();old=prefs.getAll();FileUtil.incoming="{config:[],prefers:{theme:'new',long:1234567890123,float:2.25,set:['new']}}";if(failDb)db.failCommit=true;else prefs.failCommits=1;check(!restore()&&state().equals(before)&&prefs.getAll().equals(old),"preference/commit compensation failed");}
  seed();FileUtil.incoming="{config:[{id:30,url:'new'}],prefers:{theme:'new',long:1234567890123,float:2.25,set:['new']}}";check(restore(),"valid restore failed");check(db.getDeviceDao().items.size()==1&&db.getTrackDao().items.size()==1,"successful restore lost non-backed-up tables");check(prefs.data.get("long") instanceof Long&&prefs.data.get("long").equals(1234567890123L),"long preference truncated");check(prefs.data.get("float") instanceof Float&&prefs.data.get("set").equals(Set.of("new")),"preference types lost");
  System.out.println("PASS production backup: five insertion failures, invalid prefs, prefs disk failure, DB commit failure, success preserve Device/Track, typed settings");
 }
 static final String good="{protocol:'tv-sync-snapshot-v1',type:'history',url:'https://owned/source',history:[{key:'s@@@id@@@inside@@@5',cid:5,vodName:'New'},{key:'s@@@second@@@5',cid:5,vodName:'Two'}]}";
 static void receive(String json,String type,java.util.function.BooleanSupplier active)throws Exception{try(var response=new okhttp3.Response(200,json)){SyncSnapshot.receive(response,type,10,"https://owned/source",active);}}
 static void sync()throws Exception{
  for(String json:List.of("OK","null", "{}",good.replace("tv-sync-snapshot-v1","unknown"),good.replace("https://owned/source","https://wrong/source"),good.replace("type:'history'","type:'keep'"),good.replace("history:[","other:["),good.replace("s@@@second@@@5","s@@@id@@@inside@@@5"),good.replace("s@@@second@@@5\',cid:5","s@@@second@@@6\',cid:6"))){seed();String before=state();boolean failed=false;try{receive(json,"history",()->true);}catch(Exception e){failed=true;}check(failed&&before.equals(state()),"invalid snapshot changed data: "+json);check(db.writes==0,"invalid snapshot reached SQL writes");}
  seed();String before=state();boolean failed=false;try(var r=new okhttp3.Response(503,good)){SyncSnapshot.receive(r,"history",10,"https://owned/source",()->true);}catch(Exception e){failed=true;}check(failed&&state().equals(before),"HTTP failure lost data");
  seed();before=state();db.failTable="History";db.failAfter=1;failed=false;try{receive(good,"history",()->true);}catch(Exception e){failed=true;}check(failed&&state().equals(before),"partial history insert did not roll back");
  seed();before=state();failed=false;try{receive(good,"history",()->db.writes<1);}catch(Exception e){failed=true;}check(failed&&state().equals(before),"cancelled partial sync did not roll back");
  seed();receive(good,"history",()->true);check(db.getHistoryDao().items.size()==3&&db.getHistoryDao().items.stream().anyMatch(h->h.cid==10&&h.key.equals("s@@@id@@@inside@@@10")),"history CID/key mapping failed");check(db.getHistoryDao().items.stream().anyMatch(h->h.cid==11)&&db.getTrackDao().items.size()==1&&db.getDeviceDao().items.size()==1,"sync touched unrelated rows");
  receive("{protocol:'tv-sync-snapshot-v1',type:'history',url:'https://owned/source',history:[]}","history",()->true);check(db.getHistoryDao().items.size()==1&&db.getHistoryDao().items.get(0).cid==11,"valid empty snapshot deleted wrong scope");
  String keep="{protocol:'tv-sync-snapshot-v1',type:'keep',configs:[{id:5,type:0,url:'https://owned/source'}],keep:[{key:'s@@@new@@@5',cid:5,type:0}]}";
  seed();before=state();failed=false;try{receive(keep.replace("cid:5","cid:99"),"keep",()->true);}catch(Exception e){failed=true;}check(failed&&state().equals(before),"orphan keep deleted data");
  seed();before=state();db.failTable="Keep";db.failAfter=0;failed=false;try{receive(keep,"keep",()->true);}catch(Exception e){failed=true;}check(failed&&state().equals(before),"failed keep replacement did not roll back");
  seed();receive(keep,"keep",()->true);check(db.getKeepDao().items.size()==2&&db.getKeepDao().items.stream().anyMatch(k->k.type==1)&&db.getKeepDao().items.stream().anyMatch(k->k.key.equals("s@@@new@@@10")),"keep replace/mapping/live preservation failed");
  String exported=SyncSnapshot.export("history","{url:'https://owned/source'}");check(com.google.gson.JsonParser.parseString(exported).getAsJsonObject().get("protocol").getAsString().equals("tv-sync-snapshot-v1"),"export protocol field lost");
  failed=false;try{SyncSnapshot.export("history","{url:'missing'}");}catch(Exception e){failed=true;}check(failed,"unknown peer source exported empty destructive snapshot");
  System.out.println("PASS production sync snapshot: HTTP/old-peer/malformed/wrong-source/duplicate/orphan failures retain data; transactional insert/cancel rollback; valid empty and full replace; other sources/live/Device/Track retained");
 }
 public static void main(String[]args)throws Exception{backup();if(args.length==0||!args[0].equals("backup"))sync();}
}'''
}
for cls in ('Site','Live','Device','Track'):
 STUBS[f'com/fongmi/android/tv/bean/{cls}.java']=f'package com.fongmi.android.tv.bean;public class {cls}{{public String marker="original";}}'
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--gson-jar',type=Path);p.add_argument('--source-root',type=Path,default=ROOT);p.add_argument('--only',choices=['backup']);a=p.parse_args()
 jars=list((Path.home()/'.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson').glob('*/*/gson-*.jar'))
 jar=a.gson_jar or (jars[-1] if jars else None)
 if jar is None or not jar.is_file():p.error('Gson jar required (--gson-jar)')
 with TemporaryDirectory() as temp:
  folder=Path(temp);sources=[a.source_root/'app/src/main/java/com/fongmi/android/tv/bean/Backup.java',a.source_root/'app/src/main/java/com/fongmi/android/tv/db/BackupManager.java',ROOT/'app/src/main/java/com/fongmi/android/tv/db/SyncSnapshot.java']
  for name,body in STUBS.items():
   f=folder/name;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(body,encoding='utf-8');sources.append(f)
  classes=folder/'classes';subprocess.run(['javac','-encoding','UTF-8','-cp',str(jar),'-d',str(classes),*map(str,sources)],check=True)
  import os
  subprocess.run(['java','-cp',str(classes)+os.pathsep+str(jar),'DataSafetyProbe',*([a.only] if a.only else [])],check=True,timeout=30)
if __name__=='__main__':main()
