"""Production OkDns/ScanTask with deterministic network, worker and UI-queue doubles.
Exercises overlapping resolvers, cooldown epoch isolation, scan refresh/stop and pool ownership.
No Android device or real network. Requires javac/java. --source-root enables negative controls.
"""
from pathlib import Path
from tempfile import TemporaryDirectory
import argparse, subprocess
ROOT=Path(__file__).resolve().parents[2]
STUBS={
'androidx/annotation/NonNull.java':'package androidx.annotation;public @interface NonNull{}',
'com/github/catvod/bean/Doh.java':'package com.github.catvod.bean;public class Doh{String url;public Doh(String u){url=u;}public String getUrl(){return url;}public java.util.List<java.net.InetAddress> getHosts(){return null;}}',
'com/github/catvod/utils/Util.java':'package com.github.catvod.utils;public class Util{public static boolean containOrMatch(String a,String b){return a.equals(b);}}',
'okhttp3/HttpUrl.java':'package okhttp3;public class HttpUrl{public String value;HttpUrl(String s){value=s;}public static HttpUrl parse(String s){return s==null||s.isEmpty()?null:new HttpUrl(s);}public String host(){return "owned.invalid";}public String scheme(){return "https";}}',
'okhttp3/OkHttpClient.java':'package okhttp3;public class OkHttpClient{public Builder newBuilder(){return new Builder();}public static class Builder{public Builder connectTimeout(long t,java.util.concurrent.TimeUnit u){return this;}public Builder readTimeout(long t,java.util.concurrent.TimeUnit u){return this;}public Builder callTimeout(long t,java.util.concurrent.TimeUnit u){return this;}public OkHttpClient build(){return new OkHttpClient();}}}',
'okhttp3/Dns.java':'package okhttp3;public interface Dns{java.util.List<java.net.InetAddress> lookup(String s)throws java.net.UnknownHostException;java.util.concurrent.atomic.AtomicInteger SYSTEM_CALLS=new java.util.concurrent.atomic.AtomicInteger();Dns SYSTEM=s->{SYSTEM_CALLS.incrementAndGet();return java.util.List.of(java.net.InetAddress.getLoopbackAddress());};}',
'okhttp3/dnsoverhttps/DnsOverHttps.java':'''package okhttp3.dnsoverhttps;public class DnsOverHttps implements okhttp3.Dns{public static java.util.concurrent.CountDownLatch started=new java.util.concurrent.CountDownLatch(1);public static java.util.concurrent.Semaphore release=new java.util.concurrent.Semaphore(0);public static java.util.concurrent.atomic.AtomicInteger newCalls=new java.util.concurrent.atomic.AtomicInteger();public static volatile boolean fail=true;String url;
 public java.util.List<java.net.InetAddress> lookup(String host)throws java.net.UnknownHostException{if(url.contains("old")||host.equals("late")){started.countDown();try{if(!release.tryAcquire(5,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("DNS release timeout");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AssertionError(e);}if(url.contains("oldfail"))throw failure(host);return java.util.List.of(java.net.InetAddress.getLoopbackAddress());}newCalls.incrementAndGet();if(url.contains("newfail")&&fail)throw failure(host);return java.util.List.of(java.net.InetAddress.getLoopbackAddress());}
 static java.net.UnknownHostException failure(String host){var e=new java.net.UnknownHostException(host);e.initCause(new java.io.IOException("controlled transport failure"));return e;}
 public static class Builder{String url;public Builder client(okhttp3.OkHttpClient c){return this;}public Builder url(okhttp3.HttpUrl u){url=u.value;return this;}public Builder bootstrapDnsHosts(java.util.List<java.net.InetAddress> h){return this;}public DnsOverHttps build(){var d=new DnsOverHttps();d.url=url;return d;}}}''',
'com/fongmi/android/tv/App.java':'package com.fongmi.android.tv;public class App{public static final java.util.concurrent.BlockingQueue<Runnable> tasks=new java.util.concurrent.LinkedBlockingQueue<>();public static void post(Runnable r){tasks.add(r);}public static void drain(){Runnable r;while((r=tasks.poll())!=null)r.run();}}',
'com/fongmi/android/tv/bean/Device.java':'package com.fongmi.android.tv.bean;public class Device{public static final java.util.concurrent.atomic.AtomicInteger saves=new java.util.concurrent.atomic.AtomicInteger();public String id;Device(String id){this.id=id;}public static Device objectFrom(String s){return s.equals("empty")?null:new Device(s);}public Device save(){saves.incrementAndGet();return this;}}',
'com/fongmi/android/tv/server/Server.java':'package com.fongmi.android.tv.server;public class Server{public static Server get(){return new Server();}public String getAddress(){return "http://127.0.0.1:9978";}}',
'com/fongmi/android/tv/utils/Task.java':'package com.fongmi.android.tv.utils;public class Task{public static final java.util.List<Runnable> jobs=new java.util.ArrayList<>();public static void execute(Runnable r){jobs.add(r);}public static Thread run(int index){Runnable r=jobs.remove(index);Thread t=new Thread(r);t.setDaemon(true);t.start();return t;}}',
'com/github/catvod/net/OkHttp.java':'package com.github.catvod.net;public class OkHttp{public static okhttp3.OkHttpClient client(int t){return new okhttp3.OkHttpClient();}public static void cancel(okhttp3.OkHttpClient c,String t){}public static okhttp3.Call newCall(okhttp3.OkHttpClient c,String url,String tag){return new okhttp3.Call(url);}}',
'okhttp3/Call.java':'''package okhttp3;public class Call{public static java.util.concurrent.CountDownLatch started=new java.util.concurrent.CountDownLatch(1);public static java.util.concurrent.Semaphore release=new java.util.concurrent.Semaphore(0);public static java.util.concurrent.atomic.AtomicInteger interruptions=new java.util.concurrent.atomic.AtomicInteger();String url;public Call(String u){url=u;}public Response execute(){if(url.contains("hold")){started.countDown();try{if(!release.tryAcquire(5,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("scan release timeout");}catch(InterruptedException e){interruptions.incrementAndGet();Thread.currentThread().interrupt();return new Response("empty");}}return new Response(url.contains("empty")?"empty":url.substring(0,url.length()-"/device".length()).substring(url.substring(0,url.length()-"/device".length()).lastIndexOf('/')+1));}}''',
'okhttp3/Response.java':'package okhttp3;public class Response implements AutoCloseable{String s;Response(String s){this.s=s;}public boolean isSuccessful(){return true;}public Body body(){return new Body(s);}public void close(){}public static class Body{String s;Body(String s){this.s=s;}public String string(){return s;}}}',
'AsyncOwnershipProbe.java':'''import com.github.catvod.net.OkDns;import com.github.catvod.bean.Doh;import okhttp3.dnsoverhttps.DnsOverHttps;import com.fongmi.android.tv.utils.ScanTask;import com.fongmi.android.tv.utils.Task;import com.fongmi.android.tv.App;import com.fongmi.android.tv.bean.Device;import java.util.*;import java.util.concurrent.*;
public class AsyncOwnershipProbe{
 static void check(boolean b,String message){if(!b)throw new AssertionError(message);}static Object field(OkDns d,String name)throws Exception{var f=OkDns.class.getDeclaredField(name);f.setAccessible(true);return f.get(d);}static void retryNow(OkDns d)throws Exception{var f=OkDns.class.getDeclaredField("retryAfterNs");f.setAccessible(true);f.setLong(d,System.nanoTime()-1);}
 static Thread lookup(OkDns d,String host){Thread t=new Thread(()->{try{d.lookup(host);}catch(Exception e){throw new AssertionError(e);}});t.start();return t;}
 static void resetDns(int started){DnsOverHttps.started=new CountDownLatch(started);DnsOverHttps.release=new Semaphore(0);DnsOverHttps.fail=true;}
 static void dns()throws Exception{
  resetDns(3);OkDns dns=new OkDns();dns.setDoh(new Doh("https://oldfail/dns-query"));List<Thread> threads=new ArrayList<>();for(int i=0;i<3;i++)threads.add(lookup(dns,"old"));check(DnsOverHttps.started.await(3,TimeUnit.SECONDS),"old DNS not started");dns.setDoh(new Doh("https://new/dns-query"));DnsOverHttps.release.release(3);for(var t:threads)t.join(3000);check(field(dns,"doh")!=null,"old failures disabled new resolver");int calls=DnsOverHttps.newCalls.get();dns.lookup("new");check(DnsOverHttps.newCalls.get()==calls+1,"new resolver not used");
  resetDns(1);dns=new OkDns();dns.setDoh(new Doh("https://oldsuccess/dns-query"));Thread old=lookup(dns,"old");check(DnsOverHttps.started.await(3,TimeUnit.SECONDS),"old success not pending");dns.setDoh(new Doh("https://newfail/dns-query"));dns.lookup("one");dns.lookup("two");DnsOverHttps.release.release();old.join(3000);check(((Integer)field(dns,"dohFailures"))==2,"old success reset new resolver failure count");dns.lookup("three");check(field(dns,"doh")==null,"three failures not bounded");calls=DnsOverHttps.newCalls.get();dns.lookup("system");check(DnsOverHttps.newCalls.get()==calls,"cooldown did not use SYSTEM");retryNow(dns);DnsOverHttps.fail=false;dns.lookup("recovered");check(field(dns,"doh")!=null&&((Integer)field(dns,"dohFailures"))==0,"cooldown resolver did not recover");dns.setDoh(new Doh(""));retryNow(dns);dns.lookup("system");check(field(dns,"doh")==null,"system selection resurrected stale resolver");
  // A cooldown reuses the same resolver instance, so identity alone is insufficient.
  resetDns(1);dns=new OkDns();dns.setDoh(new Doh("https://newfail/dns-query"));old=lookup(dns,"late");check(DnsOverHttps.started.await(3,TimeUnit.SECONDS),"late lookup not started");dns.lookup("one");dns.lookup("two");dns.lookup("three");retryNow(dns);DnsOverHttps.fail=false;dns.lookup("recovered");DnsOverHttps.fail=true;dns.lookup("one");dns.lookup("two");DnsOverHttps.release.release();old.join(3000);check(((Integer)field(dns,"dohFailures"))==2,"prior cooldown epoch success reset current counter");dns.lookup("three");check(field(dns,"doh")==null,"retry epoch did not observe three failures");
  System.out.println("PASS production DoH: old failure/success isolation, bounded failures, SYSTEM cooldown/recovery/reset, same-instance retry epoch isolation");
 }
 static void join(Thread t)throws Exception{t.join(3000);check(!t.isAlive(),"scan owner not finished");}static class Listener implements ScanTask.Listener{List<String> found=new ArrayList<>();int finished;public void onFind(Device d){found.add(d.id);}public void onFinished(){finished++;}}
 static void scan()throws Exception{
  App.tasks.clear();Task.jobs.clear();Device.saves.set(0);Listener l=new Listener();ScanTask s=new ScanTask(l);s.start("http://owned/old");join(Task.run(0));check(App.tasks.size()==2,"old callbacks missing");s.start("http://owned/new");App.drain();check(l.found.isEmpty()&&l.finished==0&&Device.saves.get()==0,"late old callbacks published/saved after refresh");join(Task.run(0));App.drain();check(l.found.equals(List.of("new"))&&l.finished==1&&Device.saves.get()==1,"current scan failed: "+l.found+" finished="+l.finished+" saves="+Device.saves.get());s.start("http://owned/stopped");join(Task.run(0));s.stop();App.drain();check(l.found.equals(List.of("new"))&&l.finished==1&&Device.saves.get()==1,"stopped scan published/saved");
  App.tasks.clear();Task.jobs.clear();l=new Listener();s=new ScanTask(l);s.start("http://owned/old");s.start("http://owned/hold");okhttp3.Call.started=new CountDownLatch(1);okhttp3.Call.release=new Semaphore(0);okhttp3.Call.interruptions.set(0);Thread newer=Task.run(1);check(okhttp3.Call.started.await(3,TimeUnit.SECONDS),"new scan pool not registered");join(Task.run(0));check(okhttp3.Call.interruptions.get()==0,"stale run shut down newer pool");okhttp3.Call.release.release();join(newer);App.drain();check(l.found.equals(List.of("hold"))&&l.finished==1,"new pool/results lost to stale owner");s.stop();
  System.out.println("PASS production scan: generation-gated UI callbacks and Device.save, refresh/stop isolation, stale-run cannot shut down new pool");
 }
 public static void main(String[]args)throws Exception{if(args.length==0||args[0].equals("dns"))dns();if(args.length==0||args[0].equals("scan"))scan();}
}'''
}
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,default=ROOT);p.add_argument('--only',choices=['dns','scan']);a=p.parse_args()
 with TemporaryDirectory() as temp:
  folder=Path(temp);sources=[a.source_root/'catvod/src/main/java/com/github/catvod/net/OkDns.java',a.source_root/'app/src/main/java/com/fongmi/android/tv/utils/ScanTask.java']
  for name,body in STUBS.items():
   f=folder/name;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(body,encoding='utf-8');sources.append(f)
  classes=folder/'classes';subprocess.run(['javac','-encoding','UTF-8','-d',str(classes),*map(str,sources)],check=True)
  subprocess.run(['java','-cp',str(classes),'AsyncOwnershipProbe',*([a.only] if a.only else [])],check=True,timeout=30)
if __name__=='__main__':main()
